DBookmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import bookmark.views
from bookmark.views import BookmarkListView

urlpatterns = [
    path('', BookmarkListView.as_view(), name='home'),
    path('', bookmark.views.list_bookmark, name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),     # accounts:register
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
]

bookmark/urls.py
from django.urls import path

from bookmark import views
from bookmark.views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, \
    BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    # path('', BookmarkListView.as_view(), name='list'),  # bookmark:list
    path('list2/', views.list_bookmark, name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),  # bookmark:add
    # path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),   # bookmark:detail
    path('detail2/<int:pk>/', views.detail_bookmark, name='detail'),   # bookmark:detail
    path('edit/<int:pk>/', BookmarkUpdateView.as_view(), name='edit'),      # bookmark:edit
    # path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),    # bookmark:delete
    path('delete/<int:pk>/', views.delete_bookmark, name='delete'), # bookmark:delete
]

accounts/models.py
from django.conf import settings
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=20)

    def __str__(self):
        return f'{self.nickname}({self.user.username})'

bookmark/models.py
from django.db import models
from django.shortcuts import resolve_url

from accounts.models import Profile


class Bookmark(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=10)
    url = models.URLField()

    def __str__(self):
        return f'{self.name} : {self.url}'

    def get_absolute_url(self):
        return resolve_url('bookmark:detail', pk=self.pk)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import models

from accounts.models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '영어 소문자 대문자, 숫자만 가능'
    }))
    nickname = forms.CharField(label='별명')

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)  # ('username', 'email',)

    def save(self):
        user = super().save()
        new_profile = Profile.objects.create(
            user=user,
            nickname=self.cleaned_data.get('nickname')  # self.cleaned_date['nickname']
        )
        return new_profile


class LoginForm(models.ModelForm):
    password = forms.CharField(label='패스워드', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')

accounts/views.py
from django.contrib.auth import logout, authenticate, login, REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.forms import RegisterForm, LoginForm


def register(request):
    if request.method == 'POST':    # 정보를 입력하고 POST로 넘겼을 때
        form = RegisterForm(request.POST)
        if form.is_valid():
            profile = form.save()
            return render(request, 'accounts/register_done.html', {'profile': profile})
    else:                           # 처음 빈 폼 화면
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

def my_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get(REDIRECT_FIELD_NAME) or 'bookmark:list')
        else:
            return render(request, 'accounts/login_fail.html')
    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})

@login_required
def my_logout(request):
    logout(request)
    return redirect('bookmark:list')

bookmark/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from accounts.models import Profile
from bookmark.models import Bookmark

class BookmarkListView(ListView):
    model = Bookmark
    # bookmark_list.html , {'bookmark_list' : Bookmark.objects.all()}

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:   # 로그인 하면, 로그인한 사용자의 북마크만 보이기
            # user -> profile -> bookmark_list
            profile = Profile.objects.get(user=user)    # user -> profile
            bookmark_list = Bookmark.objects.filter(profile=profile)    # profile -> bookmark_list
        else:
            # bookmark_list = Bookmark.objects.all()    # 로그인 안하면, 북마크 다 보이이기
           bookmark_list = Bookmark.objects.none()     # 로그인 안하면, 북마크 보이지 말기
        return bookmark_list

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['profile', 'name', 'url']    # '__all__'
    template_name_suffix = '_create'        # bookmark_form.html -> bookmark_create.html
    success_url = reverse_lazy('bookmark:list')

    def get_initial(self):
        # user -> profile
        user = self.request.user
        profile = Profile.objects.get(user=user)
        return {'profile': profile}

class BookmarkDetailView(LoginRequiredMixin, DetailView):
    model = Bookmark

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['name', 'url']    # '__all__'
    template_name_suffix = '_update'    # bookmark_update.html
    # success_url = reverse_lazy('bookmark:list')   # success_url 없으면 model의 get_absolute_url() 호출

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

def list_bookmark(request):

    # 로그인 사용자 확인하기
    user = request.user
    if user.is_authenticated:    # 로그인 되어있으면
        profile = Profile.objects.get(user=user)
        bookmark_list = Bookmark.objects.filter(profile=profile)    # 그 사용자의 북마크 가져오기
    else:    # 로그인 안되어 있으면
        bookmark_list = Bookmark.objects.none()     # 북마크 없는 것 가져오기

    return render(request, 'bookmark/bookmark_list.html', {'bookmark_list' : bookmark_list})


def detail_bookmark(request, pk):
    bookmark = Bookmark.objects.get()
    return render(request, 'bookmark/bookmark_detail.html', {'bookmark':bookmark})

def delete_bookmark(request, pk):
    if request.method == 'POST':    # 삭제 버튼 눌렀을 때
        bookmark = Bookmark.objects.get(pk=pk)
        bookmark.delete()   # DELETE FROM table WHERE 조건
        return redirect('bookmark:list')
    else:       # 처음 bookmark_delete.html 요청
        bookmark = Bookmark.objects.get(pk=pk)
        return render(request, 'bookmark/bookmark_confirm_delete.html', {'bookmark':bookmark})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login" class="btn btn-info">
    </form>
{% endblock %}

accounts/templates/accounts/login_fail.html
{% extends 'base.html' %}

{% block title %}logout{% endblock %}

{% block content %}
    Login Fil.
    <p><a href="{% url 'accounts:register' %}" class="btn btn-primary">register</a></p>
    <p><a href="{% url 'accounts:login' %}" class="btn btn-warning">login</a></p>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register" class="btn btn-primary">
    </form>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block content %}
    {{ profile }}님, 환영합니다.
    <a href="{% url 'accounts:login' %}">로그인</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}delete Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
        {{ bookmark }}를 지우시겠습니까?
    </div>
    <input type="submit" value="삭제" class="btn btn-danger">
    <input type="button" value="뒤로가기" onclick="history.back();" class="btn btn-light">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Add Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.profile.as_hidden }}
    <p>{{ form.name.label_tag }} {{ form.name }}</p>
    <p>{{ form.url.label_tag }} {{ form.url }}</p>
    <input type="submit" value="Add" class="btn btn-success">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}
<h1>{{ bookmark.name }}</h1>
<a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a>
<a href="{% url 'bookmark:list' %}" class="btn btn-warning">Go to Bookmark List</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
<div class="btn-group">
    {% if user.is_authenticated %}
        <a href="{% url 'bookmark:add' %}" class="btn btn-success">Add Bookmark</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-light">logout</a>
    {% else %}
        <a href="{% url 'accounts:register' %}" class="btn btn-warning">register</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-info">login</a>
    {% endif %}
</div>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>URL</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for bookmark in bookmark_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'bookmark:detail' pk=bookmark.pk %}">{{ bookmark.name }}</a></td>
            <td><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></td>
            <td><a href="{% url 'bookmark:edit' pk=bookmark.pk %}" class="btn btn-primary btn-sm">Edit</a></td>
            <td><a href="{% url 'bookmark:delete' pk=bookmark.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}edit Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="edit" class="btn btn-primary">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>